name: Despliegue a Github Pages del SPA con Vite

on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4
      
      - name: Configurar NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Instalar Dependencias
        run: npm install
      
      - name: Obtener Nombre del Repositorio
        id: repo-name
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "Repositorio: $REPO_NAME"
      
      - name: Compilar Proyecto
        env:
          DEPLOY_BASE_URL: '/'
        run: |
          echo "Usando base URL: $DEPLOY_BASE_URL"
          npm run build
      
      - name: Generar 404 html
        run: cp ./dist/index.html ./dist/404.html
      
      - name: Configurar Github Pages
        uses: actions/configure-pages@v5
      
      - name: Subir Compilado a Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      
      - name: Publicar Página en Github Pages
        id: deployment
        uses: actions/deploy-pages@v4